// utils/emojiCode.js
// Convert short emoji codes used by the backend (e.g. ":herb:") to actual emoji glyphs.

export const emojiMap = {
  ':herb:': '🌿',
  ':beach:': '🏖️',
  ':beach_with_umbrella:': '🏖️',
  ':person_climbing:': '🧗',
  ':mountain:': '⛰️',
  ':cityscape:': '🏙️',
  ':city_dusk:': '🌆',
  ':fork_and_knife:': '🍽️',
  ':art:': '🎨',
  ':book:': '📚',
  ':sun:': '☀️',
  ':snow:': '❄️',
  ':tent:': '⛺',
  ':sailboat:': '⛵',
  ':airplane:': '✈️',
  ':bus:': '🚌',
  ':train:': '🚂',
  ':car:': '🚗',
  ':family:': '👨‍👩‍👧‍👦',
  ':heart:': '❤️',
  ':moneybag:': '💰',
  ':sparkles:': '✨',
  ':lion:': '🦁',
  ':classical_building:': '🏛️',
  ':european_castle:': '🏰',
  ':mountain_snow:': '⛰️',
  ':person_in_lotus_position:': '🧘',
  ':island:': '🏝️',
  ':briefcase:': '💼',
  ':palm_tree:': '🌴',
  ':pray:': '🙏',
  ':seedling:': '🌱',
  ':earth_africa:': '🌍',
  ':compass:': '🧭',
  ':person_getting_massage:': '💆',
  ':gem:': '💎',
  ':park:': '🏞️',
  ':national_park:': '🏕️',
  ':ship:': '🚢',
  ':ocean:': '🌊',
  ':camping:': '⛺',
  ':bicycle:': '🚴',
  ':bicyclist:': '🚴',
  ':hiking_boot:': '🥾',
  ':sunrise:': '🌅',
  ':sunset:': '🌇',
  ':stars:': '⭐',
  ':moon:': '🌙',
  ':camera:': '📷',
  ':shopping_bags:': '🛍️',
  ':performing_arts:': '🎭',
  ':ski:': '⛷️',
  ':school_satchel:': '🎒',
  ':soccer:': '⚽',
  ':basketball:': '🏀',
  ':volleyball:': '🏐',
  ':tennis:': '🎾',
  ':surfing:': '🏄',
  ':handshake:': '🤝',
  ':couple_with_heart:': '💑',
  ':couple:': '👫',
  ':people_holding_hands:': '👫',
  ':ear_of_rice:': '🌾',
  ':rice_scene:': '🌾',
  ':shinto_shrine:': '⛩️',
  ':mosque:': '🕌',
  ':synagogue:': '🕍',
  ':hindu_temple:': '🛕',
  ':crown:': '👑',
  ':ring:': '💍',
  ':wine_glass:': '🍷',
  ':tropical_drink:': '🍹',
  ':jeep:': '🚙',
  ':motor_boat:': '🛥️',
  ':kayak:': '🛶',
  ':parachute:': '🪂',
  ':camping:': '🏕️',
  ':desert:': '🏜️',
  ':snowflake:': '❄️',
  ':volcano:': '🌋',
  ':fireworks:': '🎆',
  ':balloon:': '🎈',
  ':tada:': '🎉',
  ':confetti_ball:': '🎊',
  ':carousel_horse:': '🎠',
  ':ferris_wheel:': '🎡',
  ':roller_coaster:': '🎢',
};

export const convertEmojiCode = (emojiCode) => {
  if (!emojiCode) return '📍';
  const key = emojiCode.toLowerCase();
  return emojiMap[key] || emojiCode || '📍';
};

export default convertEmojiCode;
