/* ============================================================================
 * LOCALIZAÇÃO PT-PT
 * ----------------------------------------------------------------------------
 * Traduz nomes de países e cidades para Português de Portugal na CAMADA DE
 * EXIBIÇÃO. O backend/BD guardam os nomes no idioma original (ex.: "Spain").
 * Para não quebrar os endpoints que filtram por nome (ex.: /cities/by-country),
 * mantemos o valor INTERNO em inglês e só traduzimos o que o utilizador vê.
 *
 * Importante (TripWizard): nos <select> o `value`/estado continua com o nome
 * original EN; apenas o texto do <option> passa por translateCountry().
 * ========================================================================== */

// ── Países: Inglês → Português de Portugal (242, alinhado com a API) ──────
const COUNTRY_PT = {
  'Afghanistan': 'Afeganistão',
  'Albania': 'Albânia',
  'Algeria': 'Argélia',
  'American Samoa': 'Samoa Americana',
  'Andorra': 'Andorra',
  'Angola': 'Angola',
  'Anguilla': 'Anguila',
  'Antigua and Barbuda': 'Antígua e Barbuda',
  'Argentina': 'Argentina',
  'Armenia': 'Arménia',
  'Aruba': 'Aruba',
  'Australia': 'Austrália',
  'Austria': 'Áustria',
  'Azerbaijan': 'Azerbaijão',
  'Bahamas, The': 'Baamas',
  'Bahrain': 'Barém',
  'Bangladesh': 'Bangladeche',
  'Barbados': 'Barbados',
  'Belarus': 'Bielorrússia',
  'Belgium': 'Bélgica',
  'Belize': 'Belize',
  'Benin': 'Benim',
  'Bermuda': 'Bermudas',
  'Bhutan': 'Butão',
  'Bolivia': 'Bolívia',
  'Bonaire, Sint Eustatius, and Saba': 'Bonaire, Santo Eustáquio e Saba',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Botswana': 'Botsuana',
  'Brazil': 'Brasil',
  'Brunei': 'Brunei',
  'Bulgaria': 'Bulgária',
  'Burkina Faso': 'Burquina Faso',
  'Burma': 'Mianmar',
  'Burundi': 'Burúndi',
  'Cabo Verde': 'Cabo Verde',
  'Cambodia': 'Camboja',
  'Cameroon': 'Camarões',
  'Canada': 'Canadá',
  'Cayman Islands': 'Ilhas Caimão',
  'Central African Republic': 'República Centro-Africana',
  'Chad': 'Chade',
  'Chile': 'Chile',
  'China': 'China',
  'Christmas Island': 'Ilha do Natal',
  'Colombia': 'Colômbia',
  'Comoros': 'Comores',
  'Congo (Brazzaville)': 'Congo (Brazzaville)',
  'Congo (Kinshasa)': 'Congo (Quinxassa)',
  'Cook Islands': 'Ilhas Cook',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Croácia',
  'Cuba': 'Cuba',
  'Curaçao': 'Curaçau',
  'Cyprus': 'Chipre',
  'Czechia': 'Chéquia',
  'Côte d’Ivoire': 'Costa do Marfim',
  'Denmark': 'Dinamarca',
  'Djibouti': 'Jibuti',
  'Dominica': 'Domínica',
  'Dominican Republic': 'República Dominicana',
  'Ecuador': 'Equador',
  'Egypt': 'Egito',
  'El Salvador': 'El Salvador',
  'Equatorial Guinea': 'Guiné Equatorial',
  'Eritrea': 'Eritreia',
  'Estonia': 'Estónia',
  'Eswatini': 'Essuatíni',
  'Ethiopia': 'Etiópia',
  'Falkland Islands (Islas Malvinas)': 'Ilhas Falkland (Malvinas)',
  'Faroe Islands': 'Ilhas Feroé',
  'Fiji': 'Fiji',
  'Finland': 'Finlândia',
  'France': 'França',
  'French Guiana': 'Guiana Francesa',
  'French Polynesia': 'Polinésia Francesa',
  'Gabon': 'Gabão',
  'Gambia, The': 'Gâmbia',
  'Gaza Strip': 'Faixa de Gaza',
  'Georgia': 'Geórgia',
  'Germany': 'Alemanha',
  'Ghana': 'Gana',
  'Gibraltar': 'Gibraltar',
  'Greece': 'Grécia',
  'Greenland': 'Gronelândia',
  'Grenada': 'Granada',
  'Guadeloupe': 'Guadalupe',
  'Guam': 'Guame',
  'Guatemala': 'Guatemala',
  'Guernsey': 'Guernesey',
  'Guinea': 'Guiné',
  'Guinea-Bissau': 'Guiné-Bissau',
  'Guyana': 'Guiana',
  'Haiti': 'Haiti',
  'Honduras': 'Honduras',
  'Hong Kong': 'Hong Kong',
  'Hungary': 'Hungria',
  'Iceland': 'Islândia',
  'India': 'Índia',
  'Indonesia': 'Indonésia',
  'Iran': 'Irão',
  'Iraq': 'Iraque',
  'Ireland': 'Irlanda',
  'Isle of Man': 'Ilha de Man',
  'Israel': 'Israel',
  'Italy': 'Itália',
  'Jamaica': 'Jamaica',
  'Japan': 'Japão',
  'Jersey': 'Jérsia',
  'Jordan': 'Jordânia',
  'Kazakhstan': 'Cazaquistão',
  'Kenya': 'Quénia',
  'Kiribati': 'Quiribáti',
  'Korea, North': 'Coreia do Norte',
  'Korea, South': 'Coreia do Sul',
  'Kosovo': 'Kosovo',
  'Kuwait': 'Kuwait',
  'Kyrgyzstan': 'Quirguistão',
  'Laos': 'Laos',
  'Latvia': 'Letónia',
  'Lebanon': 'Líbano',
  'Lesotho': 'Lesoto',
  'Liberia': 'Libéria',
  'Libya': 'Líbia',
  'Liechtenstein': 'Listenstaine',
  'Lithuania': 'Lituânia',
  'Luxembourg': 'Luxemburgo',
  'Macau': 'Macau',
  'Madagascar': 'Madagáscar',
  'Malawi': 'Maláui',
  'Malaysia': 'Malásia',
  'Maldives': 'Maldivas',
  'Mali': 'Mali',
  'Malta': 'Malta',
  'Marshall Islands': 'Ilhas Marshall',
  'Martinique': 'Martinica',
  'Mauritania': 'Mauritânia',
  'Mauritius': 'Maurícia',
  'Mayotte': 'Maiote',
  'Mexico': 'México',
  'Micronesia, Federated States of': 'Estados Federados da Micronésia',
  'Moldova': 'Moldávia',
  'Monaco': 'Mónaco',
  'Mongolia': 'Mongólia',
  'Montenegro': 'Montenegro',
  'Montserrat': 'Monserrate',
  'Morocco': 'Marrocos',
  'Mozambique': 'Moçambique',
  'Namibia': 'Namíbia',
  'Nauru': 'Nauru',
  'Nepal': 'Nepal',
  'Netherlands': 'Países Baixos',
  'New Caledonia': 'Nova Caledónia',
  'New Zealand': 'Nova Zelândia',
  'Nicaragua': 'Nicarágua',
  'Niger': 'Níger',
  'Nigeria': 'Nigéria',
  'Niue': 'Niuê',
  'Norfolk Island': 'Ilha Norfolk',
  'North Macedonia': 'Macedónia do Norte',
  'Northern Mariana Islands': 'Ilhas Marianas do Norte',
  'Norway': 'Noruega',
  'Oman': 'Omã',
  'Pakistan': 'Paquistão',
  'Palau': 'Palau',
  'Panama': 'Panamá',
  'Papua New Guinea': 'Papua-Nova Guiné',
  'Paraguay': 'Paraguai',
  'Peru': 'Peru',
  'Philippines': 'Filipinas',
  'Pitcairn Islands': 'Ilhas Pitcairn',
  'Poland': 'Polónia',
  'Portugal': 'Portugal',
  'Puerto Rico': 'Porto Rico',
  'Qatar': 'Catar',
  'Reunion': 'Reunião',
  'Romania': 'Roménia',
  'Russia': 'Rússia',
  'Rwanda': 'Ruanda',
  'Saint Barthelemy': 'São Bartolomeu',
  'Saint Helena, Ascension, and Tristan da Cunha': 'Santa Helena, Ascensão e Tristão da Cunha',
  'Saint Kitts and Nevis': 'São Cristóvão e Neves',
  'Saint Lucia': 'Santa Lúcia',
  'Saint Martin': 'São Martinho',
  'Saint Pierre and Miquelon': 'São Pedro e Miquelão',
  'Saint Vincent and the Grenadines': 'São Vicente e Granadinas',
  'Samoa': 'Samoa',
  'San Marino': 'São Marinho',
  'Sao Tome and Principe': 'São Tomé e Príncipe',
  'Saudi Arabia': 'Arábia Saudita',
  'Senegal': 'Senegal',
  'Serbia': 'Sérvia',
  'Seychelles': 'Seicheles',
  'Sierra Leone': 'Serra Leoa',
  'Singapore': 'Singapura',
  'Sint Maarten': 'São Martinho (Sint Maarten)',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovénia',
  'Solomon Islands': 'Ilhas Salomão',
  'Somalia': 'Somália',
  'South Africa': 'África do Sul',
  'South Georgia And South Sandwich Islands': 'Ilhas Geórgia do Sul e Sandwich do Sul',
  'South Georgia and South Sandwich Islands': 'Ilhas Geórgia do Sul e Sandwich do Sul',
  'South Sudan': 'Sudão do Sul',
  'Spain': 'Espanha',
  'Sri Lanka': 'Sri Lanca',
  'Sudan': 'Sudão',
  'Suriname': 'Suriname',
  'Svalbard': 'Svalbard',
  'Sweden': 'Suécia',
  'Switzerland': 'Suíça',
  'Syria': 'Síria',
  'Taiwan': 'Taiwan',
  'Tajikistan': 'Tajiquistão',
  'Tanzania': 'Tanzânia',
  'Thailand': 'Tailândia',
  'Timor-Leste': 'Timor-Leste',
  'Togo': 'Togo',
  'Tonga': 'Tonga',
  'Trinidad and Tobago': 'Trindade e Tobago',
  'Tunisia': 'Tunísia',
  'Turkey': 'Turquia',
  'Turkmenistan': 'Turquemenistão',
  'Turks and Caicos Islands': 'Ilhas Turcas e Caicos',
  'Tuvalu': 'Tuvalu',
  'U.S. Virgin Islands': 'Ilhas Virgens dos Estados Unidos',
  'Uganda': 'Uganda',
  'Ukraine': 'Ucrânia',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'United Kingdom': 'Reino Unido',
  'United States': 'Estados Unidos',
  'Uruguay': 'Uruguai',
  'Uzbekistan': 'Uzbequistão',
  'Vanuatu': 'Vanuatu',
  'Vatican City': 'Vaticano',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietname',
  'Virgin Islands, British': 'Ilhas Virgens Britânicas',
  'Wallis and Futuna': 'Wallis e Futuna',
  'West Bank': 'Cisjordânia',
  'Yemen': 'Iémen',
  'Zambia': 'Zâmbia',
  'Zimbabwe': 'Zimbabué',
};

// ── Cidades com tradução comum em PT-PT (as restantes mantêm o original,
//    como é natural em português — ex.: "Bangkok" é igual). ────────────────
const CITY_PT = {
  'Lisbon': 'Lisboa',
  'Porto': 'Porto',
  'Aveiro': 'Aveiro',
  'Sintra': 'Sintra',
  'Cascais': 'Cascais',
  'Coimbra': 'Coimbra',
  'Braga': 'Braga',
  'Faro': 'Faro',
  'Funchal': 'Funchal',
  'Ponta Delgada': 'Ponta Delgada',
  'Madrid': 'Madrid',
  'Barcelona': 'Barcelona',
  'Seville': 'Sevilha',
  'Valencia': 'Valência',
  'Malaga': 'Málaga',
  'Cordoba': 'Córdova',
  'Bilbao': 'Bilbau',
  'Zaragoza': 'Saragoça',
  'Alicante': 'Alicante',
  'Palma': 'Palma',
  'Tenerife': 'Tenerife',
  'Gran Canaria': 'Grã-Canária',
  'Paris': 'Paris',
  'Marseille': 'Marselha',
  'Lyon': 'Lião',
  'Bordeaux': 'Bordéus',
  'Toulouse': 'Tolosa',
  'Strasbourg': 'Estrasburgo',
  'Rome': 'Roma',
  'Milan': 'Milão',
  'Venice': 'Veneza',
  'Naples': 'Nápoles',
  'Florence': 'Florença',
  'Turin': 'Turim',
  'Genoa': 'Génova',
  'London': 'Londres',
  'Edinburgh': 'Edimburgo',
  'Glasgow': 'Glásgua',
  'Prague': 'Praga',
  'Vienna': 'Viena',
  'Warsaw': 'Varsóvia',
  'Krakow': 'Cracóvia',
  'Munich': 'Munique',
  'Cologne': 'Colónia',
  'Frankfurt': 'Francoforte',
  'Hamburg': 'Hamburgo',
  'Berlin': 'Berlim',
  'Amsterdam': 'Amesterdão',
  'Rotterdam': 'Roterdão',
  'The Hague': 'Haia',
  'Brussels': 'Bruxelas',
  'Antwerp': 'Antuérpia',
  'Ghent': 'Gante',
  'Copenhagen': 'Copenhaga',
  'Stockholm': 'Estocolmo',
  'Helsinki': 'Helsínquia',
  'Athens': 'Atenas',
  'Moscow': 'Moscovo',
  'Saint Petersburg': 'São Petersburgo',
  'Beijing': 'Pequim',
  'Shanghai': 'Xangai',
  'Guangzhou': 'Cantão',
  'Tokyo': 'Tóquio',
  'Kyoto': 'Quioto',
  'Seoul': 'Seul',
  'Mexico City': 'Cidade do México',
  'Bogota': 'Bogotá',
  'New York': 'Nova Iorque',
  'Montreal': 'Montreal',
  'Cape Town': 'Cidade do Cabo',
  'Johannesburg': 'Joanesburgo',
  'Nairobi': 'Nairóbi',
  'Accra': 'Acra',
  'Dakar': 'Dacar',
  'Tunis': 'Tunes',
  'Algiers': 'Argel',
  'Tripoli': 'Trípoli',
  'Amman': 'Amã',
  'Jerusalem': 'Jerusalém',
  'Beirut': 'Beirute',
  'Baghdad': 'Bagdade',
  'Tehran': 'Teerão',
  'Riyadh': 'Riade',
  'Abu Dhabi': 'Abu Dabi',
  'Istanbul': 'Istambul',
  'Ankara': 'Ancara',
  'Kyiv': 'Kiev',
  'Minsk': 'Minsque',
  'Bucharest': 'Bucareste',
  'Budapest': 'Budapeste',
  'Belgrade': 'Belgrado',
  'Sofia': 'Sófia',
  'Zagreb': 'Zagrebe',
  'Ljubljana': 'Liubliana',
  'Skopje': 'Escópia',
  'Zurich': 'Zurique',
  'Geneva': 'Genebra',
  'Basel': 'Basileia',
  'Bern': 'Berna',
  'Salzburg': 'Salisburgo',
  'Marrakesh': 'Marraquexe',
  'Casablanca': 'Casablanca',
  'Brasilia': 'Brasília',
  'Rio de Janeiro': 'Rio de Janeiro',
  'Sao Paulo': 'São Paulo',
  'Santiago': 'Santiago',
};

/**
 * Traduz um nome de país (EN) para Português de Portugal.
 * Se não houver tradução, devolve o original.
 */
export const translateCountry = (name) => {
  if (!name || typeof name !== 'string') return name || '';
  return COUNTRY_PT[name] || name;
};

/**
 * Traduz um nome de cidade para Português de Portugal (se existir
 * tradução comum). Devolve o original caso contrário.
 */
export const translateCity = (name) => {
  if (!name || typeof name !== 'string') return name || '';
  return CITY_PT[name] || name;
};

/**
 * Traduz uma string composta "Cidade, País" (ou só um deles) exibida
 * nos cards/detalhes, mantendo o formato e traduzindo cada parte.
 * Ex.: "Seville, Spain" → "Sevilha, Espanha"
 */
export const translatePlace = (raw) => {
  if (!raw || typeof raw !== 'string') return raw || '';
  return raw
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const city = translateCity(part);
      if (city !== part) return city;
      const country = translateCountry(part);
      return country !== part ? country : part;
    })
    .join(', ');
};

/**
 * Traduz um array de nomes (países ou cidades) mantendo a ordem.
 */
export const translateList = (list) =>
  Array.isArray(list) ? list.map((item) => translatePlace(String(item))) : list;

/**
 * Devuelve o nome PT-PT para exibição num <select> mas preserva o valor
 * interno. Uso: `<option value={original}>{ptLabel(original)}</option>`.
 */
export const ptLabel = (name) => translateCountry(name);